version: '3.7'

networks:
  gitlab-network:
    name: gitlab-network
    ipam:
      config:
        - subnet: 10.0.85.0/24

volumes:
  gitlab-cfg:
    name: gitlab-cfg
    external: false
  gitlab-log:
    name: gitlab-log
    external: false
  gitlab-opt:
    name: gitlab-opt
    external: false
  runner-data:
    name: runner-data
    external: false

services:
  gitlab-web:
    image: gitlab/gitlab-ee:latest
    container_name: gitlab-web
    hostname: gitlab.devsecops.lab
    volumes:
      - './hosts:/etc/hosts'
      - 'gitlab-cfg:/etc/gitlab'
      - 'gitlab-log:/var/log/gitlab'
      - 'gitlab-opt:/var/opt/gitlab'
    ports:
      - '2222:22'
      - '8080:80'
      - '8443:443'
      - '4567:4567'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        gitlab_rails['gitlab_shell_ssh_port'] = 2222
        registry_external_url 'http://gitlab.devsecops.lab:4567'
        registry['enable'] = true
        unicorn['socket'] = '/opt/gitlab/var/unicorn/gitlab.socket'
    networks:
      gitlab-network:
         ipv4_address: 10.0.85.10

  gitlab-runners:
    image: gitlab/gitlab-runner:latest
    container_name: gitlab-runner
    hostname: runner.devsecops.lab
    volumes:
      - './hosts:/etc/hosts'
      - 'runner-data:/etc/gitlab-runner:Z'
      - '/var/run/docker.sock:/var/run/docker.sock'
    networks:
      gitlab-network:
         ipv4_address: 10.0.85.11

