version: '3.7'

services:
  gitlab-web:
    image: gitlab/gitlab-ee:latest
    container_name: gitlab-web
    hostname: gitlab.devsecops.lab
    volumes:
      - './hosts:/etc/hosts'
      - './gitlab-config:/etc/gitlab'
      - './gitlab-logs:/var/log/gitlab'
      - './gitlab-data:/var/opt/gitlab'
    ports:
      - '2222:22'
      - '8080:80'
      - '8443:443'
      - '4567:4567'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        gitlab_rails['gitlab_shell_ssh_port'] = 2222
        registry_external_url 'http://localhost:4567'
        registry['enable'] = true
        unicorn['socket'] = '/opt/gitlab/var/unicorn/gitlab.socket'
    networks:
      gitlab-network:
         ipv4_address: 10.0.80.10

  gitlab-runners:
    image: gitlab/gitlab-runner:latest
    container_name: gitlab-runner
    hostname: runner.devsecops.lab
    volumes:
      - './hosts:/etc/hosts'
      - './gitlab-runner-config:/etc/gitlab-runner:Z'
      - '/var/run/docker.sock:/var/run/docker.sock'
    networks:
      gitlab-network:
         ipv4_address: 10.0.80.11

networks:
  gitlab-network:
    name: gitlab-network
    ipam:
      config:
        - subnet: 10.0.80.0/24
